### ISSUE TITLE
Checksum error downloading data from Ensembl release 113

### ISSUE THREAD

**Issue by khiron** [cogent3/ensembl_cli#167]
Ensembl-tui fails to download from release 113 while checking checksums

Sample cfg that elicits the problem

```
[remote path]
path = pub
host = ftp.ensembl.org
[local path]
staging_path=mammals_download_113
install_path=mammals_install_113
[release]
release=113
[loxodonta_africana]
db=core
[compara]
homologies=

```

Resulting stdout 

```bash
(venv) ➜  ensembl eti download -c download_error.cfg
Downloading genomes ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:-- 0:00:02
loxodonta_... 🧬🧬  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:-- 0:00:00
Traceback (most recent call last):
  File "/home2/richard/projects/ensembl/venv/bin/eti", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home2/richard/projects/ensembl/venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home2/richard/projects/ensembl/venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home2/richard/projects/ensembl/venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home2/richard/projects/ensembl/venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home2/richard/projects/ensembl/venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home2/richard/projects/ensembl/venv/lib/python3.12/site-packages/ensembl_tui/cli.py", line 239, in download
    elt_download.download_species(config, debug, verbose, progress=progress)
  File "/home2/richard/projects/ensembl/venv/lib/python3.12/site-packages/ensembl_tui/_download.py", line 93, in download_species
    elt_ftp.download_data(
  File "/home2/richard/projects/ensembl/venv/lib/python3.12/site-packages/ensembl_tui/_ftp_download.py", line 87, in download_data
    all_checksums[str(path.parent)] = elt_util.get_signature_data(path)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home2/richard/projects/ensembl/venv/lib/python3.12/site-packages/ensembl_tui/_util.py", line 293, in get_signature_data
    return _sig_load_funcs[path.name](path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home2/richard/projects/ensembl/venv/lib/python3.12/site-packages/ensembl_tui/_util.py", line 143, in load_ensembl_checksum
    s, b, p = line.split()
    ^^^^^^^
ValueError: too many values to unpack (expected 3)
```

Checking the checksum files generated by release 112 of ensembl lines have 3 space delimited elements

release 112 example checklist
```
57682 757740 Bos_mutus.BosGru_v2.0.dna.nonchromosomal.fa.gz
57682 757740 Bos_mutus.BosGru_v2.0.dna.toplevel.fa.gz
47938 455591 Bos_mutus.BosGru_v2.0.dna_rm.nonchromosomal.fa.gz
47938 455591 Bos_mutus.BosGru_v2.0.dna_rm.toplevel.fa.gz
58548 810625 Bos_mutus.BosGru_v2.0.dna_sm.nonchromosomal.fa.gz
58548 810625 Bos_mutus.BosGru_v2.0.dna_sm.toplevel.fa.gz
31464     5 README
```
 
checksum files generated by release 114 of ensembl lines have 4 space delimited elements

release 113 example checklist

```
11807 748446 /hps/nobackup/flicek/ensembl/production/release_dumps/release-113/ftp_dumps/redump_vert/vertebrates/fasta/procavia_capensis/dna/Procavia_capensis.proCap1.dna.nonchromosomal.fa.gz Procavia_capensis.proCap1.dna.nonchromosomal.fa.gz
11807 748446 /hps/nobackup/flicek/ensembl/production/release_dumps/release-113/ftp_dumps/redump_vert/vertebrates/fasta/procavia_capensis/dna/Procavia_capensis.proCap1.dna.toplevel.fa.gz Procavia_capensis.proCap1.dna.toplevel.fa.gz
23281 556428 /hps/nobackup/flicek/ensembl/production/release_dumps/release-113/ftp_dumps/redump_vert/vertebrates/fasta/procavia_capensis/dna/Procavia_capensis.proCap1.dna_rm.nonchromosomal.fa.gz Procavia_capensis.proCap1.dna_rm.nonchromosomal.fa.gz
23281 556428 /hps/nobackup/flicek/ensembl/production/release_dumps/release-113/ftp_dumps/redump_vert/vertebrates/fasta/procavia_capensis/dna/Procavia_capensis.proCap1.dna_rm.toplevel.fa.gz Procavia_capensis.proCap1.dna_rm.toplevel.fa.gz
18519 798170 /hps/nobackup/flicek/ensembl/production/release_dumps/release-113/ftp_dumps/redump_vert/vertebrates/fasta/procavia_capensis/dna/Procavia_capensis.proCap1.dna_sm.nonchromosomal.fa.gz Procavia_capensis.proCap1.dna_sm.nonchromosomal.fa.gz
18519 798170 /hps/nobackup/flicek/ensembl/production/release_dumps/release-113/ftp_dumps/redump_vert/vertebrates/fasta/procavia_capensis/dna/Procavia_capensis.proCap1.dna_sm.toplevel.fa.gz Procavia_capensis.proCap1.dna_sm.toplevel.fa.gz
35067     5 /hps/nobackup/flicek/ensembl/production/release_dumps/release-113/ftp_dumps/redump_vert/vertebrates/fasta/procavia_capensis/dna/README README
```

**Comment by khiron** [comment]
Following is the content of the config file I used

```
[remote path]
path = pub
host = ftp.ensembl.org
[local path]
staging_path=mammals_download_113
install_path=mammals_install_113
[release]
release=113
[loxodonta_africana]
db=core
[procavia_capensis]
db=core
[echinops_telfairi] 
db=core
[dasypus_novemcinctus] 
db=core
[choloepus_hoffmanni]
db=core
[ursus_maritimus]
db=core
[ursus_americanus]
db=core
[ailuropoda_melanoleuca]
db=core
[mustela_putorius_furo]
db=core
[canis_lupus_dingo]
db=core
[canis_lupus_familiaris]
db=core
[vulpes_vulpes]
db=core
[panthera_pardus]
db=core
[panthera_leo]
db=core
[panthera_tigris_altaica]
db=core
[felis_catus]
db=core 
[equus_caballus]
db=core
[equus_asinus]
db=core
[monodon_monoceros]
db=core
[delphinapterus_leucas]
db=core
[phocoena_sinus]
db=core
[tursiops_truncatus]
db=core
[physeter_catodon]
db=core
[balaenoptera_musculus]
db=core
[ovis_aries_rambouillet]
db=core
[capra_hircus]
db=core
[bos_mutus]
db=core
[bos_grunniens]
db=core
[bison_bison_bison]
db=core
[bos_taurus]
db=core
[moschus_moschiferus]
db=core
[cervus_hanglu_yarkandensis]
db=core
[sus_scrofa]
db=core
[catagonus_wagneri]
db=core
[camelus_dromedarius]
db=core
[vicugna_pacos]
db=core
[rhinolophus_ferrumequinum]
db=core
[pteropus_vampyrus]
db=core 
[myotis_lucifugus]
db=core
[erinaceus_europaeus]
db=core
[mesocricetus_auratus]
db=core
[microtus_ochrogaster]
db=core
[peromyscus_maniculatus_bairdii]
db=core
[mus_spretus]
db=core
[mus_spicilegus]
db=core 
[mus_musculus]
db=core
[mus_caroli]
db=core
[mus_pahari]
db=core
[rattus_norvegicus]
db=core
[nannospalax_galili]
db=core
[jaculus_jaculus]
db=core
[dipodomys_ordii]
db=core
[chinchilla_lanigera]
db=core 
[octodon_degus]
db=core
[cavia_porcellus]
db=core
[urocitellus_parryii]
db=core
[ictidomys_tridecemlineatus]
db=core
[marmota_marmota_marmota]
db=core
[sciurus_vulgaris]
db=core
[oryctolagus_cuniculus]
db=core
[ochotona_princeps]
db=core
[pan_troglodytes]
db=core
[pan_paniscus] 
db=core
[homo_sapiens]
db=core
[gorilla_gorilla]
db=core
[pongo_abelii]
db=core
[nomascus_leucogenys]
db=core
[cercocebus_atys]
db=core
[mandrillus_leucophaeus]
 db=core
[papio_anubis]
db=core
[macaca_mulatta]
db=core
[macaca_fascicularis]
db=core
[macaca_nemestrina]
db=core
[chlorocebus_sabaeus]
db=core
[rhinopithecus_roxellana]
db=core
[rhinopithecus_bieti]
db=core
[cebus_imitator]
db=core
[saimiri_boliviensis_boliviensis]
db=core
[aotus_nancymaae]
db=core
[callithrix_jacchus]
db=core
[carlito_syrichta]
db=core
[prolemur_simus]
db=core
[propithecus_coquereli]
db=core
[microcebus_murinus]
db=core
[otolemur_garnettii]
db=core
[tupaia_belangeri]
db=core
[sorex_araneus]
db=core
[compara]
homologies=
```

**Comment by GavinHuttley** [comment]
fixed in df533e4
